var f;f||=typeof Module != 'undefined' ? Module : {};var aa=[],ba="./this.program",ca=globalThis.document?.currentScript?.src,da="",ea;try{da=(new URL(".",ca)).href}catch{}ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),l=console.error.bind(console),n,ha=!1,q,t,u,ia,v,w,y,z,ja;
function ka(){var a=A.buffer;q=new Int8Array(a);u=new Int16Array(a);t=new Uint8Array(a);ia=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);y=new Float32Array(a);z=new Float64Array(a);ja=new BigInt64Array(a);new BigUint64Array(a)}function la(a){f.onAbort?.(a);a="Aborted("+a+")";l(a);ha=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ma;
async function na(a){if(!n)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==ma&&n)a=new Uint8Array(n);else throw"both async and sync fetching of the wasm failed";return a}async function oa(a,b){try{var c=await na(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),la(d)}}
async function pa(a){var b=ma;if(!n)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return oa(b,a)}class qa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ra=a=>{for(;0<a.length;)a.shift()(f)},sa=[],ta=[],ua=()=>{var a=f.preRun.shift();ta.push(a)},B=0,C=null,va=!0,wa=new TextDecoder,xa=(a,b,c)=>{for(c=b+c;a[b]&&!(b>=c);)++b;return b},E=(a,b)=>a?wa.decode(t.subarray(a,xa(t,a,b))):"",F=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|
h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;g++}}d[b]=0;return b-e},G=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ya=[],za=[0,document,window],H=a=>{a=2<a?E(a):a;return za[a]||document.querySelector(a)},Aa=a=>0>za.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};
function I(a){var b=J.fc[a];b.target.removeEventListener(b.hc,b.Kc,b.nc);J.fc.splice(a,1)}function Ba(){if(navigator.userActivation?navigator.userActivation.isActive:J.zc&&J.Vc.wc){var a=J.kc;J.kc=[];for(var b of a)b.Bc(...b.Gc)}}function K(a){if(!a.target)return-4;if(a.ic)a.Kc=function(c){++J.zc;J.Vc=a;Ba();a.pc(c);Ba();--J.zc},a.target.addEventListener(a.hc,a.Kc,a.nc),J.fc.push(a);else for(var b=0;b<J.fc.length;++b)J.fc[b].target==a.target&&J.fc[b].hc==a.hc&&I(b--);return 0}
var J={cd:0,hd:0,Ac:0,vc:0,Fc:0,Dc:0,yc:0,fd:0,kd:0,ed:0,gd:0,ld:0,rd:0,Cc:0,nd(){for(;J.fc.length;)I(J.fc.length-1);J.kc=[]},zc:0,kc:[],dd(a,b,c){function d(g,h){if(g.length!=h.length)return!1;for(var k in g)if(g[k]!=h[k])return!1;return!0}for(var e of J.kc)if(e.Bc==a&&d(e.Gc,c))return;J.kc.push({Bc:a,Qc:b,Gc:c});J.kc.sort((g,h)=>g.Qc<h.Qc)},od(a){J.kc=J.kc.filter(b=>b.Bc!=a)},fc:[],bd:(a,b)=>{for(var c=0;c<J.fc.length;++c)J.fc[c].target!=a||b&&b!=J.fc[c].hc||I(c--)},pd(a){let b=!1;for(let c=0;c<
J.fc.length;++c){const d=J.fc[c];d.target===a.target&&d.mc===a.mc&&d.ic===a.ic&&d.oc===a.oc&&(I(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ca=(a,b,c,d,e,g)=>{J.yc||(J.yc=L(256));a={target:H(a),hc:g,mc:e,oc:b,ic:d,pc:h=>{var k=h.target.id?h.target.id:"",m=J.yc,p=h.target;F(p?p==window?"#window":p==screen?"#screen":p?.nodeName||"":"",m+0,128);F(k,m+128,128);M.get(d)(e,m,b)&&h.preventDefault()},nc:c};return K(a)},Da=(a,b,c,d,e,
g)=>{J.Ac||(J.Ac=L(160));a={target:H(a),hc:g,mc:e,oc:b,ic:d,pc:h=>{var k=J.Ac;z[k>>3]=h.timeStamp;var m=k>>2;v[m+2]=h.location;q[k+12]=h.ctrlKey;q[k+13]=h.shiftKey;q[k+14]=h.altKey;q[k+15]=h.metaKey;q[k+16]=h.repeat;v[m+5]=h.charCode;v[m+6]=h.keyCode;v[m+7]=h.which;F(h.key||"",k+32,32);F(h.code||"",k+64,32);F(h.char||"",k+96,32);F(h.locale||"",k+128,32);M.get(d)(e,k,b)&&h.preventDefault()},nc:c};return K(a)},Ea=(a,b,c)=>{z[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;
v[d+5]=b.clientY;q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;u[2*d+14]=b.button;u[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=Aa(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},Fa=(a,b,c,d,e,g)=>{J.vc||(J.vc=L(64));a=H(a);return K({target:a,wc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,hc:g,mc:e,oc:b,ic:d,pc:h=>{Ea(J.vc,h,a);M.get(d)(e,J.vc,b)&&h.preventDefault()},nc:c})},Ga=(a,b,c,d)=>{J.Dc||(J.Dc=L(36));a=H(a);return K({target:a,hc:"resize",
mc:10,oc:b,ic:d,pc:e=>{if(e.target==a){var g=document.body;if(g){var h=J.Dc;v[h>>2]=0;v[h+4>>2]=g.clientWidth;v[h+8>>2]=g.clientHeight;v[h+12>>2]=innerWidth;v[h+16>>2]=innerHeight;v[h+20>>2]=outerWidth;v[h+24>>2]=outerHeight;v[h+28>>2]=pageXOffset|0;v[h+32>>2]=pageYOffset|0;M.get(d)(10,h,b)&&e.preventDefault()}}},nc:c})},Ha=(a,b,c,d,e,g)=>{J.Cc||(J.Cc=L(1552));a=H(a);return K({target:a,wc:"touchstart"==g||"touchend"==g,hc:g,mc:e,oc:b,ic:d,pc:h=>{var k={},m=h.touches;for(var p of m)p.Nc=p.Pc=0,k[p.identifier]=
p;for(var r of h.changedTouches)r.Nc=1,k[r.identifier]=r;for(var x of h.targetTouches)k[x.identifier].Pc=1;m=J.Cc;z[m>>3]=h.timeStamp;q[m+12]=h.ctrlKey;q[m+13]=h.shiftKey;q[m+14]=h.altKey;q[m+15]=h.metaKey;p=m+16;r=Aa(a);x=0;for(let D of Object.values(k))if(k=p>>2,v[k]=D.identifier,v[k+1]=D.screenX,v[k+2]=D.screenY,v[k+3]=D.clientX,v[k+4]=D.clientY,v[k+5]=D.pageX,v[k+6]=D.pageY,q[p+28]=D.Nc,q[p+29]=D.Pc,v[k+8]=D.clientX-(r.left|0),v[k+9]=D.clientY-(r.top|0),p+=48,31<++x)break;v[m+8>>2]=x;M.get(d)(e,
m,b)&&h.preventDefault()},nc:c})},Ia=(a,b,c,d)=>{J.Fc||(J.Fc=L(96));return K({target:a,wc:!0,hc:"wheel",mc:9,oc:b,ic:d,pc:e=>{var g=J.Fc;Ea(g,e,a);z[g+64>>3]=e.deltaX;z[g+72>>3]=e.deltaY;z[g+80>>3]=e.deltaZ;v[g+88>>2]=e.deltaMode;M.get(d)(9,g,b)&&e.preventDefault()},nc:c})},N,Ja=a=>{a.Hc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")},Ka=a=>{a.Oc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")},La=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Ma=1,O=[],P=[],Na=[],Oa=[],Q=[],R=[],S=[],T=[],Pa=[],Qa=[],Ra={},Sa={},Ta=4,Ua=0,Va=a=>{for(var b=Ma++,c=a.length;c<b;c++)a[c]=null;return b},V=(a,b,c,d)=>{for(var e=0;e<a;e++){var g=N[c](),h=g&&Va(d);g?(g.name=h,d[h]=g):U||=1282;v[b+4*e>>2]=h}},Xa=(a,b)=>{a.Mc||(a.Mc=a.getContext,a.getContext=function(d,e){e=a.Mc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?Wa(c,b):0},Wa=
(a,b)=>{var c=Va(T),d={handle:c,attributes:b,version:b.ad,lc:a};a.canvas&&(a.canvas.Uc=d);T[c]=d;if("undefined"==typeof b.Jc||b.Jc)if((a=d)||(a=W),!a.$c){a.$c=!0;b=a.lc;b.qc=b.getExtension("WEBGL_multi_draw");b.Zc=b.getExtension("EXT_polygon_offset_clamp");b.Yc=b.getExtension("EXT_clip_control");b.Tc=b.getExtension("WEBGL_polygon_mode");Ja(b);Ka(b);2<=a.version&&(b.Ic=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ic)b.Ic=b.getExtension("EXT_disjoint_timer_query");for(var e of La(b))e.includes("lose_context")||
e.includes("debug")||b.getExtension(e)}return c},U,W,Ya=["default","low-power","high-performance"],Za={},ab=()=>{if(!$a){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Za)void 0===Za[b]?delete a[b]:a[b]=Za[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);$a=c}return $a},$a,bb=a=>{va||(f.onExit?.(a),ha=!0);throw new qa(a);},cb=[null,[],[]],db=[],eb=()=>{var a=La(N);
return a=a.concat(a.map(b=>"GL_"+b))},fb=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(U||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>W.version){U||=1282;return}d=eb().length;break;case 33307:case 33308:if(2>W.version){U||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":U||=1280;return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:U||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:q[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(g){U||=
1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${g})`);return}}break;default:U||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;w[b>>2]=c;w[b+4>>2]=(c-w[b>>2])/4294967296;break;case 0:v[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:q[b]=d?1:0}}else U||=1281},X=a=>{var b=G(a)+1,c=L(b);c&&F(a,c,b);return c},gb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),
Y=a=>{a-=5120;return 0==a?q:1==a?t:2==a?u:4==a?v:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?w:ia},hb=(a,b,c,d,e)=>{a=Y(a);b=d*((Ua||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Ta-1&-Ta);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Z=a=>{var b=N.Wc;if(b){var c=b.rc[a];"number"==typeof c&&(b.rc[a]=c=N.getUniformLocation(b,b.Rc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},ib=(a,b=[])=>M.get(a)(...b);
for(let a=0;32>a;++a)db.push(Array(a));f.noExitRuntime&&(va=f.noExitRuntime);f.print&&(fa=f.print);f.printErr&&(l=f.printErr);f.wasmBinary&&(n=f.wasmBinary);f.arguments&&(aa=f.arguments);f.thisProgram&&(ba=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();
var jb={232372:()=>{var a=navigator.userAgent.match(/Firefox\/(\d+)/);return a?a[1]|0:0},232474:()=>{var a=f.canvas.getContext("webgl2").getExtension("WEBGL_compressed_texture_astc").getSupportedProfiles();return(0<=a.indexOf("ldr")?1:0)|(0<=a.indexOf("hdr")?2:0)}},kb,L,lb,A,M,mb={ib:()=>{},u:function(){return 0},db:()=>{},fb:function(){return 0},cb:()=>{},gb:function(){},jb:()=>la(""),Za:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();
w[a>>2]=60*Math.max(g,e);v[b>>2]=Number(g!=e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(F(a,c,17),F(b,d,17)):(F(a,d,17),F(b,c,17))},$a:function(a,b,c){if(!(0<=a&&3>=a))return 28;ja[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},mb:function(){return"undefined"!==typeof process&&"win32"==process.platform},nb:function(a,b){a=E(a,b);if("undefined"!==typeof process&&a in
process.Xc){a=process.Xc[a];b=G(a)+1;var c=L(b);F(a,c,b);return c}return 0},w:(a,b,c)=>{ya.length=0;for(var d;d=t[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;ya.push(112==d?w[c>>2]:106==d?ja[c>>3]:105==d?v[c>>2]:z[c>>3]);c+=e?8:4}return jb[a](...ya)},s:(a,b,c)=>{a=H(a);if(!a)return-4;v[b>>2]=a.width;v[c>>2]=a.height},q:()=>devicePixelRatio,aa:(a,b,c)=>{a=H(a);if(!a)return-4;a=Aa(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},ab:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=
2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-A.buffer.byteLength+65535)/65536|0;try{A.grow(d);ka();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},Yb:(a,b,c,d)=>Ca(a,b,c,d,12,"blur"),p:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},J:(a,b,c,d)=>Ca(a,b,c,d,13,"focus"),Wa:(a,b,c,d)=>Da(a,b,c,d,2,"keydown"),Ua:(a,b,c,d)=>Da(a,b,c,d,3,"keyup"),Qb:(a,b,c,d)=>Fa(a,b,c,d,5,"mousedown"),Ab:(a,b,c,d)=>Fa(a,b,c,d,8,
"mousemove"),Kb:(a,b,c,d)=>Fa(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>Ga(a,b,c,d),_a:(a,b,c,d)=>Ha(a,b,c,d,23,"touchend"),Ya:(a,b,c,d)=>Ha(a,b,c,d,24,"touchmove"),hb:(a,b,c,d)=>Ha(a,b,c,d,22,"touchstart"),qb:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Ia(a,b,c,d):-1:-4,Ta:()=>W&&W.lc&&W.attributes.Lc?0:-3,ua:(a,b)=>{var c=b>>2;b={alpha:!!q[b+0],depth:!!q[b+1],stencil:!!q[b+2],antialias:!!q[b+3],premultipliedAlpha:!!q[b+4],preserveDrawingBuffer:!!q[b+5],powerPreference:Ya[v[c+2]],failIfMajorPerformanceCaveat:!!q[b+
12],ad:v[c+4],jd:v[c+5],Jc:q[b+24],Lc:q[b+25],md:v[c+7],qd:q[b+32]};a=H(a);return!a||b.Lc?0:Xa(a,b)},Zb:a=>{W==a&&(W=0);W===T[a]&&(W=null);"object"==typeof J&&J.bd(T[a].lc.canvas);T[a]?.lc.canvas&&(T[a].lc.canvas.Uc=void 0);T[a]=null},rb:(a,b)=>{a=T[a];b=E(b);b.startsWith("GL_")&&(b=b.slice(3));"WEBGL_draw_instanced_base_vertex_base_instance"==b&&Ja(N);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&Ka(N);"WEBGL_multi_draw"==b&&(N.qc=N.getExtension("WEBGL_multi_draw"));"EXT_polygon_offset_clamp"==
b&&(N.Zc=N.getExtension("EXT_polygon_offset_clamp"));"EXT_clip_control"==b&&(N.Yc=N.getExtension("EXT_clip_control"));"WEBGL_polygon_mode"==b&&(N.Tc=N.getExtension("WEBGL_polygon_mode"));return!!a.lc.getExtension(b)},sb:()=>W?W.handle:0,ja:a=>{W=T[a];f.ctx=N=W?.lc;return!a||N?0:-5},kb:(a,b)=>{var c=0,d=0,e;for(e of ab()){var g=b+c;w[a+d>>2]=g;c+=F(e,g,Infinity)+1;d+=4}return 0},lb:(a,b)=>{var c=ab();w[a>>2]=c.length;a=0;for(var d of c)a+=G(d)+1;w[b>>2]=a;return 0},z:a=>{bb(a)},v:()=>52,eb:()=>52,
bb:function(){return 70},t:(a,b,c,d)=>{for(var e=0,g=0;g<c;g++){var h=w[b>>2],k=w[b+4>>2];b+=8;for(var m=0;m<k;m++){var p=a,r=t[h+m],x=cb[p];0===r||10===r?(p=1===p?fa:l,r=xa(x,0),r=wa.decode(x.buffer?x.subarray(0,r):new Uint8Array(x.slice(0,r))),p(r),x.length=0):x.push(r)}e+=k}w[d>>2]=e;return 0},j:a=>N.activeTexture(a),ya:(a,b)=>{N.attachShader(P[a],R[b])},A:(a,b)=>{35051==a?N.xc=b:35052==a&&(N.jc=b);N.bindBuffer(a,O[b])},B:(a,b,c)=>{N.bindBufferBase(a,b,O[c])},Ub:(a,b,c,d,e)=>{N.bindBufferRange(a,
b,O[c],d,e)},r:(a,b)=>{N.bindFramebuffer(a,Na[b])},Hb:(a,b)=>{N.bindRenderbuffer(a,Oa[b])},o:(a,b)=>{N.bindTexture(a,Q[b])},ob:(a,b)=>{N.bindTransformFeedback(a,Qa[b])},m:a=>{N.bindVertexArray(S[a])},Jb:(a,b)=>N.blendFunc(a,b),Qa:(a,b,c,d,e,g,h,k,m,p)=>N.blitFramebuffer(a,b,c,d,e,g,h,k,m,p),Pb:(a,b,c,d)=>{c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d)},Ob:(a,b,c,d)=>{c&&N.bufferSubData(a,b,t,d,c)},Ma:a=>N.checkFramebufferStatus(a),Pa:a=>N.clear(a),Ia:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),Ja:(a,b,
c)=>{N.clearBufferfv(a,b,y,c>>2)},La:(a,b,c)=>{N.clearBufferiv(a,b,v,c>>2)},Ka:(a,b,c)=>{N.clearBufferuiv(a,b,w,c>>2)},y:(a,b,c,d)=>N.clearColor(a,b,c,d),C:a=>N.clearDepth(a),F:a=>{N.compileShader(R[a])},n:(a,b,c,d,e,g,h,k,m)=>{N.jc||!k?N.compressedTexSubImage2D(a,b,c,d,e,g,h,k,m):N.compressedTexSubImage2D(a,b,c,d,e,g,h,t,m,k)},W:(a,b,c,d,e,g,h,k,m,p,r)=>{N.jc?N.compressedTexSubImage3D(a,b,c,d,e,g,h,k,m,p,r):N.compressedTexSubImage3D(a,b,c,d,e,g,h,k,m,t,r,p)},Tb:(a,b,c,d,e)=>N.copyBufferSubData(a,
b,c,d,e),Ea:(a,b,c,d,e,g,h,k)=>N.copyTexSubImage2D(a,b,c,d,e,g,h,k),Da:(a,b,c,d,e,g,h,k,m)=>N.copyTexSubImage3D(a,b,c,d,e,g,h,k,m),Ca:()=>{var a=Va(P),b=N.createProgram();b.name=a;b.uc=b.sc=b.tc=0;b.Ec=1;P[a]=b;return a},I:a=>{var b=Va(R);R[b]=N.createShader(a);return b},Vb:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.xc&&(N.xc=0),d==N.jc&&(N.jc=0))}},Ba:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):U||=1281}},H:a=>{if(a){var b=
R[a];b?(N.deleteShader(b),R[a]=null):U||=1281}},ga:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(N.deleteTexture(e),e.name=0,Q[d]=null)}},O:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];N.deleteVertexArray(S[d]);S[d]=null}},x:a=>N.depthFunc(a),D:(a,b)=>N.depthRange(a,b),g:a=>N.disable(a),V:(a,b,c)=>{N.drawArrays(a,b,c)},R:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},zb:(a,b,c,d,e)=>{N.Hc.drawArraysInstancedBaseInstanceWEBGL(a,b,c,d,e)},Ha:(a,b)=>{for(var c=db[a],d=0;d<a;d++)c[d]=v[b+4*
d>>2];N.drawBuffers(c)},S:(a,b,c,d)=>{N.drawElements(a,b,c,d)},Q:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},e:(a,b,c,d,e,g,h)=>{N.Hc.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,d,e,g,h)},U:(a,b,c,d,e,g)=>{N.drawElements(a,d,e,g)},b:a=>N.enable(a),N:a=>{N.enableVertexAttribArray(a)},Db:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,Oa[d])},Cb:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},Bb:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},Wb:(a,b)=>{V(a,b,"createBuffer",
O)},Eb:(a,b)=>{V(a,b,"createFramebuffer",Na)},tb:(a,b)=>{V(a,b,"createQuery",Pa)},Ib:(a,b)=>{V(a,b,"createRenderbuffer",Oa)},ha:(a,b)=>{V(a,b,"createTexture",Q)},pb:(a,b)=>{V(a,b,"createTransformFeedback",Qa)},P:(a,b)=>{V(a,b,"createVertexArray",S)},fa:a=>N.generateMipmap(a),Sb:(a,b,c)=>{c?v[c>>2]=N.getBufferParameter(a,b):U||=1281},Rb:(a,b,c,d)=>{d?c&&N.getBufferSubData(a,b,t,d,c):U||=1281},ia:(a,b)=>fb(a,b,2),f:(a,b)=>fb(a,b,0),Aa:(a,b,c,d)=>{a=N.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");
b=0<b&&d?F(a,d,b):0;c&&(v[c>>2]=b)},k:(a,b,c)=>{if(c)if(a>=Ma)U||=1281;else if(a=P[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.uc){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.uc=Math.max(a.uc,N.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.uc}else if(35722==b){if(!a.sc)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.sc=Math.max(a.sc,N.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.sc}else if(35381==b){if(!a.tc)for(d=
N.getProgramParameter(a,35382),b=0;b<d;++b)a.tc=Math.max(a.tc,N.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.tc}else v[c>>2]=N.getProgramParameter(a,b);else U||=1281},E:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,d,b):0;c&&(v[c>>2]=b)},h:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=N.getShaderParameter(R[a],b):U||=1281},c:a=>
{var b=Ra[a];if(!b){switch(a){case 7939:b=X(eb().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||(U||=1280);b=b?X(b):0;break;case 7938:b=X(`OpenGL ES 3.0 (${N.getParameter(7938)})`);break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=X(b);break;default:U||=1280}Ra[a]=b}return b},Nb:(a,b)=>{if(2>W.version)return U||=1282,0;var c=Sa[a];if(c)return 0>
b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=eb().map(X),c=Sa[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},ta:(a,b)=>N.getUniformBlockIndex(P[a],E(b)),va:(a,b)=>{b=E(b);if(a=P[a]){var c=a,d=c.rc,e=c.Sc,g;if(!d){c.rc=d={};c.Rc={};var h=N.getProgramParameter(c,35718);for(g=0;g<h;++g){var k=N.getActiveUniform(c,g);var m=k.name;k=k.size;var p=gb(m);p=0<p?m.slice(0,p):m;var r=c.Ec;c.Ec+=k;e[p]=[k,r];for(m=0;m<k;++m)d[r]=m,c.Rc[r++]=p}}c=a.rc;d=0;e=b;g=gb(b);0<g&&
(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Sc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else U||=1281;return-1},Oa:(a,b,c)=>{for(var d=db[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];N.invalidateFramebuffer(a,d)},Na:(a,b,c,d,e,g,h)=>{for(var k=db[b],m=0;m<b;m++)k[m]=v[c+4*m>>2];N.invalidateSubFramebuffer(a,k,d,e,g,h)},wa:a=>{a=P[a];N.linkProgram(a);a.rc=0;a.Sc={}},xb:(a,b,c,d)=>{N.qc.multiDrawArraysWEBGL(a,v,b>>2,v,c>>2,d)},vb:(a,b,c,d,e)=>{N.qc.multiDrawArraysInstancedWEBGL(a,
v,b>>2,v,c>>2,v,d>>2,e)},ub:(a,b,c,d,e,g)=>{N.Oc.multiDrawArraysInstancedBaseInstanceWEBGL(a,v,b>>2,v,c>>2,v,d>>2,w,e>>2,g)},yb:(a,b,c,d,e)=>{N.qc.multiDrawElementsWEBGL(a,v,b>>2,c,v,d>>2,e)},wb:(a,b,c,d,e,g)=>{N.qc.multiDrawElementsInstancedWEBGL(a,v,b>>2,c,v,d>>2,v,e>>2,g)},l:(a,b,c,d,e,g,h,k)=>{N.Oc.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,v,b>>2,c,v,d>>2,v,e>>2,v,g>>2,w,h>>2,k)},d:(a,b)=>{3317==a?Ta=b:3314==a&&(Ua=b);N.pixelStorei(a,b)},Xb:(a,b)=>{N.Tc.polygonModeWEBGL(a,b)},Mb:(a,
b)=>N.polygonOffset(a,b),Ga:a=>N.readBuffer(a),Fa:(a,b,c,d,e,g,h)=>{if(N.xc)N.readPixels(a,b,c,d,e,g,h);else{var k=Y(g);h>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);N.readPixels(a,b,c,d,e,g,k,h)}},Gb:(a,b,c,d)=>N.renderbufferStorage(a,b,c,d),Fb:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,d,e),Lb:(a,b,c,d)=>N.scissor(a,b,c,d),G:(a,b,c,d)=>{for(var e="",g=0;g<b;++g)e+=E(w[c+4*g>>2],d?w[d+4*g>>2]:void 0);N.shaderSource(R[a],e)},Z:(a,b,c,d,e,g,h,k,m)=>{if(N.jc)N.texImage2D(a,b,c,d,e,g,h,k,m);else if(m){var p=
Y(k);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);N.texImage2D(a,b,c,d,e,g,h,k,p,m)}else p=m?hb(k,h,d,e,m):null,N.texImage2D(a,b,c,d,e,g,h,k,p)},Y:(a,b,c,d,e,g,h,k,m,p)=>{if(N.jc)N.texImage3D(a,b,c,d,e,g,h,k,m,p);else if(p){var r=Y(m);N.texImage3D(a,b,c,d,e,g,h,k,m,r,p>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else N.texImage3D(a,b,c,d,e,g,h,k,m,null)},da:(a,b,c)=>N.texParameterf(a,b,c),ba:(a,b,c)=>{N.texParameterf(a,b,y[c>>2])},ea:(a,b,c)=>N.texParameteri(a,b,c),ca:(a,b,c)=>{N.texParameteri(a,b,v[c>>2])},
$:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),_:(a,b,c,d,e,g)=>N.texStorage3D(a,b,c,d,e,g),i:(a,b,c,d,e,g,h,k,m)=>{if(N.jc)N.texSubImage2D(a,b,c,d,e,g,h,k,m);else if(m){var p=Y(k);N.texSubImage2D(a,b,c,d,e,g,h,k,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=m?hb(k,h,e,g,m):null,N.texSubImage2D(a,b,c,d,e,g,h,k,m)},X:(a,b,c,d,e,g,h,k,m,p,r)=>{if(N.jc)N.texSubImage3D(a,b,c,d,e,g,h,k,m,p,r);else if(r){var x=Y(p);N.texSubImage3D(a,b,c,d,e,g,h,k,m,p,x,r>>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,
b,c,d,e,g,h,k,m,p,null)},xa:(a,b,c,d)=>{a=P[a];for(var e=[],g=0;g<b;g++)e.push(E(w[c+4*g>>2]));N.transformFeedbackVaryings(a,e,d)},sa:(a,b)=>{N.uniform1f(Z(a),b)},oa:(a,b,c)=>{b&&N.uniform1fv(Z(a),y,c>>2,b)},qa:(a,b)=>{N.uniform1i(Z(a),b)},pa:(a,b,c)=>{N.uniform2ui(Z(a),b,c)},na:(a,b,c)=>{b&&N.uniform3fv(Z(a),y,c>>2,3*b)},ra:(a,b,c,d,e)=>{N.uniform4f(Z(a),b,c,d,e)},ma:(a,b,c)=>{b&&N.uniform4fv(Z(a),y,c>>2,4*b)},a:(a,b,c)=>{a=P[a];N.uniformBlockBinding(a,b,c)},la:(a,b,c,d)=>{b&&N.uniformMatrix3fv(Z(a),
!!c,y,d>>2,9*b)},ka:(a,b,c,d)=>{b&&N.uniformMatrix4fv(Z(a),!!c,y,d>>2,16*b)},za:a=>{a=P[a];N.useProgram(a);N.Wc=a},K:(a,b)=>{N.vertexAttribDivisor(a,b)},M:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,b,c,d,e)},L:(a,b,c,d,e,g)=>{N.vertexAttribPointer(a,b,c,!!d,e,g)},Ra:(a,b,c,d)=>N.viewport(a,b,c,d),Va:function(){var a="#"+f.canvas.id,b=G(a)+1,c=L(b);F(a,c,b);return c},Xa:function(){var a=f.keyboardListeningElement||document;if(a===document)return 1;if(a===window)return 2;if("id"in a){a="#"+a.id;var b=G(a)+
1,c=L(b);F(a,c,b);return c}return 0},_b:function(a,b){function c(){var d=window.requestAnimationFrame(c);ib(a,[b])||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},Sa:function(a,b){f.canvas.style.cursor=E(a,b)}};function nb(a=[]){var b=kb;a.unshift(ba);var c=a.length,d=lb(4*(c+1)),e=d,g;for(g of a){a=w;var h=e>>2,k=g,m=G(k)+1,p=lb(m);F(k,p,m);a[h]=p;e+=4}w[e>>2]=0;try{var r=b(c,d);bb(r)}catch(x){if(!(x instanceof qa||"unwind"==x))throw x;}}
function ob(a=aa){function b(){f.calledRun=!0;if(!ha){pb.ac();f.onRuntimeInitialized?.();f.noInitialRun||nb(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();sa.push(c)}ra(sa)}}if(0<B)C=ob;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ua();ra(ta);0<B?C=ob:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var pb;
(async function(){function a(c){c=pb=c.exports;kb=f._main=c.cc;L=c.dc;lb=c.ec;A=c.$b;M=c.bc;ka();B--;f.monitorRunDependencies?.(B);0==B&&C&&(c=C,C=null,c());return pb}B++;f.monitorRunDependencies?.(B);var b={a:mb};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ma??=f.locateFile?f.locateFile("playground.wasm",da):da+"playground.wasm";return a((await pa(b)).instance)})();ob();
