
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var l={},m;for(m in f)f.hasOwnProperty(m)&&(l[m]=f[m]);var aa=[],ba="./this.program";function ca(a,b){throw b;}var u="";"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src);u=0!==u.indexOf("blob:")?u.substr(0,u.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var da=f.print||console.log.bind(console),v=f.printErr||console.warn.bind(console);for(m in l)l.hasOwnProperty(m)&&(f[m]=l[m]);l=null;
f.arguments&&(aa=f.arguments);f.thisProgram&&(ba=f.thisProgram);f.quit&&(ca=f.quit);var w;f.wasmBinary&&(w=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&ea("no native wasm support detected");var fa,ha=!1,ia=new TextDecoder("utf8");function y(a,b){if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&z[c];)++c;return ia.decode(z.subarray(a,c))}
function A(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var n=a.charCodeAt(++g);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function B(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ja(a){for(var b="";;){var c=z[a++>>0];if(!c)return b;b+=String.fromCharCode(c)}}function ka(a){var b=B(a)+1,c=la(b);A(a,C,c,b);return c}var ma,C,z,na,oa,D,E,F,G;
function pa(){var a=fa.buffer;ma=a;f.HEAP8=C=new Int8Array(a);f.HEAP16=na=new Int16Array(a);f.HEAP32=D=new Int32Array(a);f.HEAPU8=z=new Uint8Array(a);f.HEAPU16=oa=new Uint16Array(a);f.HEAPU32=E=new Uint32Array(a);f.HEAPF32=F=new Float32Array(a);f.HEAPF64=G=new Float64Array(a);f.HEAP64=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var H,qa=[],ra=[],ta=[],ua=[],va=[];function wa(){var a=f.preRun.shift();qa.unshift(a)}var J=0,xa=null,K=null;f.preloadedImages={};f.preloadedAudios={};
function ea(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";v(a);ha=!0;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function ya(){return L.startsWith("data:application/octet-stream;base64,")}var L;L="playground.wasm";if(!ya()){var za=L;L=f.locateFile?f.locateFile(za,u):u+za}function Aa(){var a=L;try{if(a==L&&w)return new Uint8Array(w);throw"both async and sync fetching of the wasm failed";}catch(b){ea(b)}}
function Ba(){return w||"function"!==typeof fetch?Promise.resolve().then(function(){return Aa()}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Aa()})}
var Ca={151860:function(a){document.title=y(a)},151897:function(a){(f.canvas.closest(".mn-container")||document.getElementById("container")).className=["mn-container",ja(a)].join(" ")},152046:function(){var a=f.keyboardListeningElement||document;if(a===document)return 1;if(a===window)return 2;if("id"in a){var b=B(a.id)+1,c=M(b);A(a.id,z,c,b);return c}return 0},152344:function(a){f.canvas.style.cursor=ja(a)},152397:function(a,b){function c(){var d=window.requestAnimationFrame(c);H.get(a).apply(null,
[b])||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},152602:function(){var a=f.canvas.id,b=B(a)+1,c=M(b);A(a,z,c,b);return c},152750:function(){var a="";if("undefined"!==typeof process)for(var b in process.kc)a+=b+"="+process.kc[b]+"\b";a+="\b";b=B(a)+1;const c=M(b);A(a,z,c,b);return c},153008:function(a){a=y(a);if("undefined"!==typeof process&&a in process.kc){a=process.kc[a];var b=B(a)+1,c=M(b);A(a,z,c,b);return c}return 0}};
function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Oc;"number"===typeof c?void 0===b.ic?H.get(c)():H.get(c)(b.ic):c(void 0===b.ic?null:b.ic)}}}var Ea=[null,[],[]],Fa={},Ga;Ga=function(){return performance.now()};var Ha=[],Ia=0;function Ja(){for(var a=N.length-1;0<=a;--a)Ka(a);N=[];La=[]}var La=[];function Ma(){if(Ia&&Na.hc)for(var a=0;a<La.length;++a){var b=La[a];La.splice(a,1);--a;b.Tc.apply(null,b.Kc)}}var N=[];
function Ka(a){var b=N[a];b.target.removeEventListener(b.Lb,b.Bc,b.Vb);N.splice(a,1)}function Oa(a){function b(d){++Ia;Na=a;Ma();a.Xb(d);Ma();--Ia}if(a.Wb)a.Bc=b,a.target.addEventListener(a.Lb,b,a.Vb),N.push(a),Pa||(ua.push(Ja),Pa=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Lb==a.Lb&&Ka(c--)}var Qa={},Pa,Na,Ra,Sa,Ta,Ua,Va=[0,document,window];function O(a){a=2<a?y(a):a;return Va[a]||document.querySelector(a)}
function Wa(a){return 0>Va.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Xa(a,b,c,d,e,g){Ra||(Ra=M(176));a={target:O(a),hc:!0,Lb:g,Wb:d,Xb:function(h){var n=Ra;G[n>>3]=h.timeStamp;var p=n>>2;D[p+2]=h.location;D[p+3]=h.ctrlKey;D[p+4]=h.shiftKey;D[p+5]=h.altKey;D[p+6]=h.metaKey;D[p+7]=h.repeat;D[p+8]=h.charCode;D[p+9]=h.keyCode;D[p+10]=h.which;A(h.key||"",z,n+44,32);A(h.code||"",z,n+76,32);A(h.char||"",z,n+108,32);A(h.locale||"",z,n+140,32);H.get(d)(e,n,b)&&h.preventDefault()},Vb:c};Oa(a)}
function Ya(a,b,c){G[a>>3]=b.timeStamp;a>>=2;D[a+2]=b.screenX;D[a+3]=b.screenY;D[a+4]=b.clientX;D[a+5]=b.clientY;D[a+6]=b.ctrlKey;D[a+7]=b.shiftKey;D[a+8]=b.altKey;D[a+9]=b.metaKey;na[2*a+20]=b.button;na[2*a+21]=b.buttons;D[a+11]=b.movementX;D[a+12]=b.movementY;c=Wa(c);D[a+13]=b.clientX-c.left;D[a+14]=b.clientY-c.top}
function Za(a,b,c,d,e,g){Sa||(Sa=M(72));a=O(a);Oa({target:a,hc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Lb:g,Wb:d,Xb:function(h){h=h||event;Ya(Sa,h,a);H.get(d)(e,Sa,b)&&h.preventDefault()},Vb:c})}
function $a(a,b,c,d){Ta||(Ta=M(36));a=O(a);Oa({target:a,Lb:"resize",Wb:d,Xb:function(e){e=e||event;if(e.target==a){var g=document.body;if(g){var h=Ta;D[h>>2]=e.detail;D[h+4>>2]=g.clientWidth;D[h+8>>2]=g.clientHeight;D[h+12>>2]=innerWidth;D[h+16>>2]=innerHeight;D[h+20>>2]=outerWidth;D[h+24>>2]=outerHeight;D[h+28>>2]=pageXOffset;D[h+32>>2]=pageYOffset;H.get(d)(10,h,b)&&e.preventDefault()}}},Vb:c})}
function ab(a,b,c,d){Ua||(Ua=M(104));Oa({target:a,hc:!0,Lb:"wheel",Wb:d,Xb:function(e){e=e||event;var g=Ua;Ya(g,e,a);G[g+72>>3]=e.deltaX;G[g+80>>3]=e.deltaY;G[g+88>>3]=e.deltaZ;D[g+96>>2]=e.deltaMode;H.get(d)(9,g,b)&&e.preventDefault()},Vb:c})}var bb=1,P=[],Q=[],cb=[],db=[],R=[],S=[],eb=[],T=[],fb=[],gb=[],hb=[1,1,2,2,4,4,4,2,3,4,8],ib={},jb={};function V(a){kb||(kb=a)}function lb(a){for(var b=bb++,c=a.length;c<b;c++)a[c]=null;return b}function mb(a){return 32-Math.clz32(0===a?0:a-1)}
function nb(a){ob=!1;for(var b=0;b<W.uc;++b){var c=W.Pb[b];if(c.Qb&&c.enabled){ob=!0;var d=c.bc;d=0<d?a*d:c.size*hb[c.type-5120]*a;var e=mb(d);var g=W.cc[e],h=W.Sb[e];W.Sb[e]=W.Sb[e]+1&63;var n=g[h];n?e=n:(n=X.getParameter(34964),g[h]=X.createBuffer(),X.bindBuffer(34962,g[h]),X.bufferData(34962,1<<e,35048),X.bindBuffer(34962,n),e=g[h]);X.bindBuffer(34962,e);X.bufferSubData(34962,0,z.subarray(c.ac,c.ac+d));c.oc.call(X,b,c.size,c.type,c.lc,c.bc,0)}}}
function pb(a,b){a.tc||(a.tc=a.getContext,a.getContext=function(d,e){e=a.tc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?qb(c,b):0}
function qb(a,b){var c=lb(T),d={Cc:c,attributes:b,version:b.Ec,Kb:a};a.canvas&&(a.canvas.zc=d);T[c]=d;("undefined"===typeof b.rc||b.rc)&&rb(d);d.uc=d.Kb.getParameter(34921);d.Pb=[];for(a=0;a<d.uc;a++)d.Pb[a]={enabled:!1,Qb:!1,size:0,type:0,lc:0,bc:0,ac:0,oc:null};a=mb(2097152);d.Sb=[];d.wc=[];d.Sb.length=d.wc.length=a+1;d.cc=[];d.mc=[];d.cc.length=d.mc.length=a+1;d.Nb=[];d.Nb.length=a+1;for(b=0;b<=a;++b){d.Nb[b]=null;d.Sb[b]=d.wc[b]=0;d.cc[b]=[];d.mc[b]=[];var e=d.cc[b],g=d.mc[b];e.length=g.length=
64;for(var h=0;64>h;++h)e[h]=g[h]=null}return c}
function rb(a){a||(a=W);if(!a.Dc){a.Dc=!0;var b=a.Kb;b.pc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Fc=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.qc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.qc)b.qc=b.getExtension("EXT_disjoint_timer_query");b.vc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var W,kb,ob,sb=["default","low-power","high-performance"];f._emscripten_webgl_get_current_context=function(){return W?W.Cc:0};function tb(a){W=T[a];f.Lc=X=W&&W.Kb;return!a||X?0:-5}f._emscripten_webgl_make_context_current=tb;var ub={};
function wb(){if(!xb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in ub)void 0===ub[b]?delete a[b]:a[b]=ub[b];var c=[];for(b in a)c.push(b+"="+a[b]);xb=c}return xb}var xb,yb=[];function Y(a,b,c,d){for(var e=0;e<a;e++){var g=X[c](),h=g&&lb(d);g?(g.name=h,d[h]=g):V(1282);D[b+4*e>>2]=h}}
function zb(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&V(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=X.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>W.version){V(1282);return}d=2*(X.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>W.version){V(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=X.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:D[b+4*a>>2]=e[a];break;case 2:F[b+4*a>>2]=e[a];break;case 4:C[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){V(1280);
v("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:V(1280);v("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;E[b>>2]=c;E[b+4>>2]=(c-E[b>>2])/4294967296;break;case 0:D[b>>2]=d;break;case 2:F[b>>2]=d;break;case 4:C[b>>0]=d?1:0}}else V(1281)}function Ab(a){var b=B(a)+1,c=M(b);A(a,z,c,b);return c}
function Bb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Cb(a){a-=5120;return 0==a?C:1==a?z:2==a?na:4==a?D:6==a?F:5==a||28922==a||28520==a||30779==a||30782==a?E:oa}function Db(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Z(a){var b=X.Ac;if(b){var c=b.Ub[a];"number"===typeof c&&(b.Ub[a]=c=X.getUniformLocation(b,b.xc[a]+(0<c?"["+c+"]":"")));return c}V(1282)}function Eb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Fb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Gb=[31,29,31,30,31,30,31,31,30,31,30,31],Hb=[31,28,31,30,31,30,31,31,30,31,30,31];function Ib(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Eb(a.getFullYear())?Gb:Hb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Jb(a,b,c,d){function e(k,t,x){for(k="number"===typeof k?k.toString():k||"";k.length<t;)k=x[0]+k;return k}function g(k,t){return e(k,t,"0")}function h(k,t){function x(vb){return 0>vb?-1:0<vb?1:0}var U;0===(U=x(k.getFullYear()-t.getFullYear()))&&0===(U=x(k.getMonth()-t.getMonth()))&&(U=x(k.getDate()-t.getDate()));return U}function n(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function p(k){k=Ib(new Date(k.Ib+1900,0,1),k.fc);var t=new Date(k.getFullYear()+1,0,4),x=n(new Date(k.getFullYear(),0,4));t=n(t);return 0>=h(x,k)?0>=h(t,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=D[d+40>>2];d={Ic:D[d>>2],Hc:D[d+4>>2],dc:D[d+8>>2],Tb:D[d+12>>2],Ob:D[d+16>>2],Ib:D[d+20>>2],ec:D[d+24>>2],fc:D[d+28>>2],Uc:D[d+32>>2],Gc:D[d+
36>>2],Jc:q?y(q):""};c=y(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in q)c=c.replace(new RegExp(r,"g"),q[r]);var I="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
sa="January February March April May June July August September October November December".split(" ");q={"%a":function(k){return I[k.ec].substring(0,3)},"%A":function(k){return I[k.ec]},"%b":function(k){return sa[k.Ob].substring(0,3)},"%B":function(k){return sa[k.Ob]},"%C":function(k){return g((k.Ib+1900)/100|0,2)},"%d":function(k){return g(k.Tb,2)},"%e":function(k){return e(k.Tb,2," ")},"%g":function(k){return p(k).toString().substring(2)},"%G":function(k){return p(k)},"%H":function(k){return g(k.dc,
2)},"%I":function(k){k=k.dc;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.Tb+Fb(Eb(k.Ib+1900)?Gb:Hb,k.Ob-1),3)},"%m":function(k){return g(k.Ob+1,2)},"%M":function(k){return g(k.Hc,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.dc&&12>k.dc?"AM":"PM"},"%S":function(k){return g(k.Ic,2)},"%t":function(){return"\t"},"%u":function(k){return k.ec||7},"%U":function(k){var t=new Date(k.Ib+1900,0,1),x=0===t.getDay()?t:Ib(t,7-t.getDay());k=new Date(k.Ib+1900,k.Ob,k.Tb);return 0>
h(x,k)?g(Math.ceil((31-x.getDate()+(Fb(Eb(k.getFullYear())?Gb:Hb,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,t)?"01":"00"},"%V":function(k){var t=new Date(k.Ib+1901,0,4),x=n(new Date(k.Ib+1900,0,4));t=n(t);var U=Ib(new Date(k.Ib+1900,0,1),k.fc);return 0>h(U,x)?"53":0>=h(t,U)?"01":g(Math.ceil((x.getFullYear()<k.Ib+1900?k.fc+32-x.getDate():k.fc+1-x.getDate())/7),2)},"%w":function(k){return k.ec},"%W":function(k){var t=new Date(k.Ib,0,1),x=1===t.getDay()?t:Ib(t,0===t.getDay()?1:7-t.getDay()+1);k=
new Date(k.Ib+1900,k.Ob,k.Tb);return 0>h(x,k)?g(Math.ceil((31-x.getDate()+(Fb(Eb(k.getFullYear())?Gb:Hb,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,t)?"01":"00"},"%y":function(k){return(k.Ib+1900).toString().substring(2)},"%Y":function(k){return k.Ib+1900},"%z":function(k){k=k.Gc;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Jc},"%%":function(){return"%"}};for(r in q)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),q[r](d)));r=Kb(c);
if(r.length>b)return 0;C.set(r,a);return r.length-1}for(var X,Lb=0;32>Lb;++Lb)yb.push(Array(Lb));function Kb(a){var b=Array(B(a)+1);A(a,b,0,b.length);return b}
var Nb={cb:function(a,b){a=y(a);return Fa.Mc(a,b)},D:function(){return 0},eb:function(){return 0},fb:function(){},a:function(){ea("")},Za:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Ga();else return-1;D[b>>2]=a/1E3|0;D[b+4>>2]=a%1E3*1E6|0;return 0},d:function(a,b,c){Ha.length=0;var d;for(c>>=2;d=z[b++];)(d=105>d)&&c&1&&c++,Ha.push(d?G[c++>>1]:D[c]),++c;return Ca[a].apply(null,Ha)},B:function(a,b,c){a=O(a);if(!a)return-4;D[b>>2]=a.width;D[c>>2]=a.height},ra:function(){return devicePixelRatio},
n:function(a,b,c){a=O(a);if(!a)return-4;a=Wa(a);G[b>>3]=a.width;G[c>>3]=a.height;return 0},Xa:function(a,b,c){z.copyWithin(a,b,b+c)},Ya:function(a){var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{fa.grow(Math.min(2147483648,d)-ma.byteLength+65535>>>16);pa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},A:function(a,b,c){a=O(a);if(!a)return-4;a.width=b;a.height=c;return 0},
bb:function(a,b,c,d){Xa(a,b,c,d,2,"keydown");return 0},Wa:function(a,b,c,d){Xa(a,b,c,d,3,"keyup");return 0},M:function(a,b,c,d){Za(a,b,c,d,5,"mousedown");return 0},qb:function(a,b,c,d){Za(a,b,c,d,8,"mousemove");return 0},Ab:function(a,b,c,d){Za(a,b,c,d,6,"mouseup");return 0},T:function(a,b,c,d){$a(a,b,c,d);return 0},hb:function(a,b,c,d){a=O(a);return"undefined"!==typeof a.onwheel?(ab(a,b,c,d),0):-1},Va:function(){return W&&W.Kb&&W.attributes.sc?0:-3},ia:function(a,b){b>>=2;b={alpha:!!D[b],depth:!!D[b+
1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+5],powerPreference:sb[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],Ec:D[b+8],Qc:D[b+9],rc:D[b+10],sc:D[b+11],Rc:D[b+12],Sc:D[b+13]};a=O(a);return!a||b.sc?0:pb(a,b)},Bb:function(a){W==a&&(W=0);W===T[a]&&(W=null);if("object"===typeof Qa)for(var b=T[a].Kb.canvas,c=0;c<N.length;++c)N[c].target!=b||Ka(c--);T[a]&&T[a].Kb.canvas&&(T[a].Kb.canvas.zc=void 0);T[a]=null},Ba:function(a){a>>=2;for(var b=0;14>b;++b)D[a+
b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=D[a+8]=D[a+10]=1},$:tb,$a:function(a,b){var c=0;wb().forEach(function(d,e){var g=b+c;e=D[a+4*e>>2]=g;for(g=0;g<d.length;++g)C[e++>>0]=d.charCodeAt(g);C[e>>0]=0;c+=d.length+1});return 0},ab:function(a,b){var c=wb();D[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});D[b>>2]=d;return 0},t:function(a){Mb(a)},F:function(){return 0},db:function(a,b,c,d){a=Fa.Pc(a);b=Fa.Nc(a,b,c);D[d>>2]=b;return 0},C:function(){},E:function(a,b,c,d){for(var e=0,g=0;g<c;g++){for(var h=
D[b+8*g>>2],n=D[b+(8*g+4)>>2],p=0;p<n;p++){var q=z[h+p],r=Ea[a];if(0===q||10===q){for(q=0;r[q]&&!(NaN<=q);)++q;q=ia.decode(r.subarray?r.subarray(0,q):new Uint8Array(r.slice(0,q)));(1===a?da:v)(q);r.length=0}else r.push(q)}e+=n}D[d>>2]=e;return 0},b:function(a){X.activeTexture(a)},Ca:function(a,b){X.attachShader(Q[a],S[b])},v:function(a,b){34962==a?X.Mb=b:34963==a&&(X.Rb=b);35051==a?X.jc=b:35052==a&&(X.Jb=b);X.bindBuffer(a,P[b])},i:function(a,b,c){X.bindBufferBase(a,b,P[c])},u:function(a,b,c,d,e){X.bindBufferRange(a,
b,P[c],d,e)},c:function(a,b){X.bindFramebuffer(a,cb[b])},H:function(a,b){X.bindRenderbuffer(a,db[b])},x:function(a,b){X.bindTexture(a,R[b])},o:function(a,b){X.bindTransformFeedback(a,gb[b])},m:function(a){X.bindVertexArray(eb[a]);a=X.getParameter(34965);X.Rb=a?a.name|0:0},J:function(a,b){X.blendFunc(a,b)},Ta:function(a,b,c,d,e,g,h,n,p,q){X.blitFramebuffer(a,b,c,d,e,g,h,n,p,q)},O:function(a,b,c,d){c?X.bufferData(a,z,d,c,b):X.bufferData(a,b,d)},N:function(a,b,c,d){X.bufferSubData(a,b,z,d,c)},Pa:function(a){return X.checkFramebufferStatus(a)},
Sa:function(a){X.clear(a)},La:function(a,b,c,d){X.clearBufferfi(a,b,c,d)},Ma:function(a,b,c){X.clearBufferfv(a,b,F,c>>2)},Oa:function(a,b,c){X.clearBufferiv(a,b,D,c>>2)},Na:function(a,b,c){X.clearBufferuiv(a,b,E,c>>2)},r:function(a,b,c,d){X.clearColor(a,b,c,d)},I:function(a){X.clearDepth(a)},jb:function(a){X.compileShader(S[a])},w:function(a,b,c,d,e,g,h,n,p){X.Jb?X.compressedTexSubImage2D(a,b,c,d,e,g,h,n,p):X.compressedTexSubImage2D(a,b,c,d,e,g,h,z,p,n)},da:function(a,b,c,d,e,g,h,n,p,q,r){X.Jb?X.compressedTexSubImage3D(a,
b,c,d,e,g,h,n,p,q,r):X.compressedTexSubImage3D(a,b,c,d,e,g,h,n,p,z,r,q)},Q:function(a,b,c,d,e){X.copyBufferSubData(a,b,c,d,e)},Ha:function(a,b,c,d,e,g,h,n){X.copyTexSubImage2D(a,b,c,d,e,g,h,n)},Ga:function(a,b,c,d,e,g,h,n,p){X.copyTexSubImage3D(a,b,c,d,e,g,h,n,p)},Fa:function(){var a=lb(Q),b=X.createProgram();b.name=a;b.$b=b.Yb=b.Zb=0;b.nc=1;Q[a]=b;return a},mb:function(a){var b=lb(S);S[b]=X.createShader(a);return b},R:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=P[d];e&&(X.deleteBuffer(e),
e.name=0,P[d]=null,d==X.Mb&&(X.Mb=0),d==X.Rb&&(X.Rb=0),d==X.jc&&(X.jc=0),d==X.Jb&&(X.Jb=0))}},Ea:function(a){if(a){var b=Q[a];b?(X.deleteProgram(b),b.name=0,Q[a]=null):V(1281)}},lb:function(a){if(a){var b=S[a];b?(X.deleteShader(b),S[a]=null):V(1281)}},pa:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=R[d];e&&(X.deleteTexture(e),e.name=0,R[d]=null)}},Y:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2];X.deleteVertexArray(eb[d]);eb[d]=null}},q:function(a){X.depthFunc(a)},l:function(a){X.disable(a)},
ca:function(a,b,c){nb(b+c);X.drawArrays(a,b,c);ob&&X.bindBuffer(34962,P[X.Mb])},aa:function(a,b,c,d){X.drawArraysInstanced(a,b,c,d)},sb:function(a,b,c,d,e){X.pc.drawArraysInstancedBaseInstanceWEBGL(a,b,c,d,e)},Ka:function(a,b){for(var c=yb[a],d=0;d<a;d++)c[d]=D[b+4*d>>2];X.drawBuffers(c)},ba:function(a,b,c,d){if(!X.Rb){var e=1*hb[c-5120]*b;var g=mb(e);var h=W.Nb[g];h?g=h:(h=X.getParameter(34965),W.Nb[g]=X.createBuffer(),X.bindBuffer(34963,W.Nb[g]),X.bufferData(34963,1<<g,35048),X.bindBuffer(34963,
h),g=W.Nb[g]);X.bindBuffer(34963,g);X.bufferSubData(34963,0,z.subarray(d,d+e));d=0}nb(b);X.drawElements(a,b,c,d);ob&&X.bindBuffer(34962,P[X.Mb]);X.Rb||X.bindBuffer(34963,null)},_:function(a,b,c,d,e){X.drawElementsInstanced(a,b,c,d,e)},j:function(a,b,c,d,e,g,h){X.pc.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,d,e,g,h)},e:function(a){X.enable(a)},X:function(a){W.Pb[a].enabled=!0;X.enableVertexAttribArray(a)},vb:function(a,b,c,d){X.framebufferRenderbuffer(a,b,c,db[d])},ub:function(a,b,c,d,
e){X.framebufferTexture2D(a,b,c,R[d],e)},tb:function(a,b,c,d,e){X.framebufferTextureLayer(a,b,R[c],d,e)},S:function(a,b){Y(a,b,"createBuffer",P)},wb:function(a,b){Y(a,b,"createFramebuffer",cb)},nb:function(a,b){Y(a,b,"createQuery",fb)},zb:function(a,b){Y(a,b,"createRenderbuffer",db)},qa:function(a,b){Y(a,b,"createTexture",R)},gb:function(a,b){Y(a,b,"createTransformFeedback",gb)},Z:function(a,b){Y(a,b,"createVertexArray",eb)},oa:function(a){X.generateMipmap(a)},P:function(a,b,c){c?D[c>>2]=X.getBufferParameter(a,
b):V(1281)},sa:function(a,b){zb(a,b,2)},k:function(a,b){zb(a,b,0)},Da:function(a,b,c,d){a=X.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,z,d,b):0;c&&(D[c>>2]=b)},z:function(a,b,c){if(c)if(a>=bb)V(1281);else if(a=Q[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.$b)for(b=0;b<X.getProgramParameter(a,35718);++b)a.$b=Math.max(a.$b,X.getActiveUniform(a,b).name.length+1);D[c>>2]=a.$b}else if(35722==b){if(!a.Yb)for(b=
0;b<X.getProgramParameter(a,35721);++b)a.Yb=Math.max(a.Yb,X.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.Yb}else if(35381==b){if(!a.Zb)for(b=0;b<X.getProgramParameter(a,35382);++b)a.Zb=Math.max(a.Zb,X.getActiveUniformBlockName(a,b).length+1);D[c>>2]=a.Zb}else D[c>>2]=X.getProgramParameter(a,b);else V(1281)},ib:function(a,b,c,d){a=X.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,z,d,b):0;c&&(D[c>>2]=b)},G:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),
D[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(S[a]),D[c>>2]=a?a.length+1:0):D[c>>2]=X.getShaderParameter(S[a],b):V(1281)},h:function(a){var b=ib[a];if(!b){switch(a){case 7939:b=X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ab(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||V(1280);b=b&&Ab(b);break;case 7938:b=Ab("OpenGL ES 3.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ab(b);break;default:V(1280)}ib[a]=b}return b},s:function(a,b){if(2>W.version)return V(1282),0;var c=jb[a];if(c)return 0>b||b>=c.length?(V(1281),0):c[b];switch(a){case 7939:return c=X.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Ab(d)}),c=jb[a]=c,0>b||b>=c.length?(V(1281),0):c[b];default:return V(1280),0}},za:function(a,b){b=y(b);if(a=Q[a]){var c=a,d=c.Ub,e=c.yc,
g;if(!d)for(c.Ub=d={},c.xc={},g=0;g<X.getProgramParameter(c,35718);++g){var h=X.getActiveUniform(c,g);var n=h.name;h=h.size;var p=Bb(n);p=0<p?n.slice(0,p):n;var q=c.nc;c.nc+=h;e[p]=[h,q];for(n=0;n<h;++n)d[q]=n,c.xc[q++]=p}c=a.Ub;d=0;e=b;g=Bb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.yc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else V(1281);return-1},Ra:function(a,b,c){for(var d=yb[b],e=0;e<b;e++)d[e]=D[c+4*e>>2];X.invalidateFramebuffer(a,d)},Qa:function(a,
b,c,d,e,g,h){for(var n=yb[b],p=0;p<b;p++)n[p]=D[c+4*p>>2];X.invalidateSubFramebuffer(a,n,d,e,g,h)},Aa:function(a){a=Q[a];X.linkProgram(a);a.Ub=0;a.yc={}},ob:function(a,b,c,d){X.vc.multiDrawArraysWEBGL(a,D,b>>2,D,c>>2,d)},pb:function(a,b,c,d,e){X.vc.multiDrawElementsWEBGL(a,D,b>>2,c,D,d>>2,e)},rb:function(a,b,c,d,e,g,h,n){X.Fc.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,D,b>>2,c,D,d>>2,D,e>>2,D,g>>2,E,h>>2,n)},g:function(a,b){X.pixelStorei(a,b)},L:function(a,b){X.polygonOffset(a,b)},Ja:function(a){X.readBuffer(a)},
Ia:function(a,b,c,d,e,g,h){if(X.jc)X.readPixels(a,b,c,d,e,g,h);else{var n=Cb(g);X.readPixels(a,b,c,d,e,g,n,h>>Db(n))}},yb:function(a,b,c,d){X.renderbufferStorage(a,b,c,d)},xb:function(a,b,c,d,e){X.renderbufferStorageMultisample(a,b,c,d,e)},K:function(a,b,c,d){X.scissor(a,b,c,d)},kb:function(a,b,c,d){for(var e="",g=0;g<b;++g){var h=d?D[d+4*g>>2]:-1;e+=y(D[c+4*g>>2],0>h?void 0:h)}X.shaderSource(S[a],e)},ga:function(a,b,c,d,e,g,h,n,p){if(X.Jb)X.texImage2D(a,b,c,d,e,g,h,n,p);else if(p){var q=Cb(n);X.texImage2D(a,
b,c,d,e,g,h,n,q,p>>Db(q))}else X.texImage2D(a,b,c,d,e,g,h,n,null)},fa:function(a,b,c,d,e,g,h,n,p,q){if(X.Jb)X.texImage3D(a,b,c,d,e,g,h,n,p,q);else if(q){var r=Cb(p);X.texImage3D(a,b,c,d,e,g,h,n,p,r,q>>Db(r))}else X.texImage3D(a,b,c,d,e,g,h,n,p,null)},ma:function(a,b,c){X.texParameterf(a,b,c)},ka:function(a,b,c){X.texParameterf(a,b,F[c>>2])},na:function(a,b,c){X.texParameteri(a,b,c)},la:function(a,b,c){X.texParameteri(a,b,D[c>>2])},ja:function(a,b,c,d,e){X.texStorage2D(a,b,c,d,e)},ha:function(a,b,
c,d,e,g){X.texStorage3D(a,b,c,d,e,g)},p:function(a,b,c,d,e,g,h,n,p){if(X.Jb)X.texSubImage2D(a,b,c,d,e,g,h,n,p);else if(p){var q=Cb(n);X.texSubImage2D(a,b,c,d,e,g,h,n,q,p>>Db(q))}else X.texSubImage2D(a,b,c,d,e,g,h,n,null)},ea:function(a,b,c,d,e,g,h,n,p,q,r){if(X.Jb)X.texSubImage3D(a,b,c,d,e,g,h,n,p,q,r);else if(r){var I=Cb(q);X.texSubImage3D(a,b,c,d,e,g,h,n,p,q,I,r>>Db(I))}else X.texSubImage3D(a,b,c,d,e,g,h,n,p,q,null)},y:function(a,b,c,d){a=Q[a];for(var e=[],g=0;g<b;g++)e.push(y(D[c+4*g>>2]));X.transformFeedbackVaryings(a,
e,d)},ya:function(a,b,c){X.uniform1fv(Z(a),F,c>>2,b)},va:function(a,b,c){X.uniform1iv(Z(a),D,c>>2,b)},xa:function(a,b,c){X.uniform3fv(Z(a),F,c>>2,3*b)},wa:function(a,b,c){X.uniform4fv(Z(a),F,c>>2,4*b)},ua:function(a,b,c,d){X.uniformMatrix3fv(Z(a),!!c,F,d>>2,9*b)},ta:function(a,b,c,d){X.uniformMatrix4fv(Z(a),!!c,F,d>>2,16*b)},f:function(a){a=Q[a];X.useProgram(a);X.Ac=a},U:function(a,b){X.vertexAttribDivisor(a,b)},W:function(a,b,c,d,e){var g=W.Pb[a];X.Mb?(g.Qb=!1,X.vertexAttribIPointer(a,b,c,d,e)):
(g.size=b,g.type=c,g.lc=!1,g.bc=d,g.ac=e,g.Qb=!0,g.oc=function(h,n,p,q,r,I){this.vertexAttribIPointer(h,n,p,r,I)})},V:function(a,b,c,d,e,g){var h=W.Pb[a];X.Mb?(h.Qb=!1,X.vertexAttribPointer(a,b,c,!!d,e,g)):(h.size=b,h.type=c,h.lc=d,h.bc=e,h.ac=g,h.Qb=!0,h.oc=function(n,p,q,r,I,sa){this.vertexAttribPointer(n,p,q,r,I,sa)})},Ua:function(a,b,c,d){X.viewport(a,b,c,d)},_a:function(a,b,c,d){return Jb(a,b,c,d)}};
(function(){function a(e){f.asm=e.exports;fa=f.asm.Cb;pa();H=f.asm.Gb;ra.unshift(f.asm.Db);J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==xa&&(clearInterval(xa),xa=null),K&&(e=K,K=null,e()))}function b(e){a(e.instance)}function c(e){return Ba().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){v("failed to asynchronously prepare wasm: "+g);ea(g)})}var d={a:Nb};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return v("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return w||"function"!==typeof WebAssembly.instantiateStreaming||ya()||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){v("wasm streaming compile failed: "+g);v("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Db).apply(null,arguments)};var M=f._malloc=function(){return(M=f._malloc=f.asm.Eb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Fb).apply(null,arguments)};var la=f.stackAlloc=function(){return(la=f.stackAlloc=f.asm.Hb).apply(null,arguments)},Ob;function Pb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Qb(){Ob||Rb();Ob||(K=Qb)};
function Rb(a){function b(){if(!Ob&&(Ob=!0,f.calledRun=!0,!ha)){Da(ra);Da(ta);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Sb){var c=a,d=f._main;c=c||[];var e=c.length+1,g=la(4*(e+1));D[g>>2]=ka(ba);for(var h=1;h<e;h++)D[(g>>2)+h]=ka(c[h-1]);D[(g>>2)+e]=0;try{var n=d(e,g);Mb(n)}catch(p){p instanceof Pb||"unwind"==p||ca(1,p)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),va.unshift(c);Da(va)}}a=a||aa;if(!(0<J)){if(f.preRun)for("function"==
typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();Da(qa);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Rb;function Mb(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ha=!0}ca(a,new Pb(a))}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Sb=!0;f.noInitialRun&&(Sb=!1);Rb();
