
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",da=(a,b)=>{throw b;},k="";"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=0!==k.indexOf("blob:")?k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):"";var ea=f.print||console.log.bind(console),m=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);
f.quit&&(da=f.quit);var u;f.wasmBinary&&(u=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&fa("no native wasm support detected");var ha,ia=!1,ja=new TextDecoder("utf8");function v(a,b){if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&x[c];)++c;return ja.decode(x.subarray(a,c))}
function y(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var n=a.charCodeAt(++g);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function z(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var ka,A,x,la,ma,B,C,D,na,E;
function oa(){var a=ha.buffer;ka=a;f.HEAP8=A=new Int8Array(a);f.HEAP16=la=new Int16Array(a);f.HEAP32=B=new Int32Array(a);f.HEAPU8=x=new Uint8Array(a);f.HEAPU16=ma=new Uint16Array(a);f.HEAPU32=C=new Uint32Array(a);f.HEAPF32=D=new Float32Array(a);f.HEAPF64=E=new Float64Array(a);f.HEAP64=na=new BigInt64Array(a);f.HEAPU64=new BigUint64Array(a)}var pa,qa=[],ra=[],sa=[],ta=[],ua=[];function va(){var a=f.preRun.shift();qa.unshift(a)}var F=0,wa=null,G=null;
function fa(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";m(a);ia=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function xa(){return H.startsWith("data:application/octet-stream;base64,")}var H;H="playground.wasm";if(!xa()){var ya=H;H=f.locateFile?f.locateFile(ya,k):k+ya}function za(){var a=H;try{if(a==H&&u)return new Uint8Array(u);throw"both async and sync fetching of the wasm failed";}catch(b){fa(b)}}
function Aa(){return u||"function"!=typeof fetch?Promise.resolve().then(function(){return za()}):fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return za()})}
var Ca={173572:(a,b)=>{document.title=v(a,b)},173613:(a,b)=>{(f.canvas.closest(".mn-container")||document.getElementById("container")).className=["mn-container",v(a,b)].join(" ")},173765:()=>{var a=f.keyboardListeningElement||document;if(a===document)return 1;if(a===window)return 2;if("id"in a){var b=z(a.id)+1,c=I(b);y(a.id,x,c,b);return c}return 0},174063:a=>{f.canvas.style.cursor=Ba(a)},174116:(a,b)=>{function c(){var d=window.requestAnimationFrame(c);pa.get(a).apply(null,[b])||window.cancelAnimationFrame(d)}
window.requestAnimationFrame(c)},174321:()=>{var a=f.canvas.id,b=z(a)+1,c=I(b);y(a,x,c,b);return c},174469:()=>{var a=navigator.userAgent.match(/Firefox\/(\d+)/);return a?a[1]|0:0},174571:()=>{var a="";if("undefined"!==typeof process)for(var b in process.oc)a+=b+"="+process.oc[b]+"\b";a+="\b";b=z(a)+1;const c=I(b);y(a,x,c,b);return c},174829:(a,b)=>{a=v(a,b);if("undefined"!==typeof process&&a in process.oc){a=process.oc[a];b=z(a)+1;var c=I(b);y(a,x,c,b);return c}return 0}};
function Da(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ea(a){for(;0<a.length;)a.shift()(f)}var Fa=[],Ga=0;function Ha(){for(var a=J.length-1;0<=a;--a)Ia(a);J=[];Ja=[]}var Ja=[];function Ka(){if(Ga&&La.mc)for(var a=0;a<Ja.length;++a){var b=Ja[a];Ja.splice(a,1);--a;b.Oc.apply(null,b.Jc)}}var J=[];function Ia(a){var b=J[a];b.target.removeEventListener(b.Zb,b.Bc,b.cc);J.splice(a,1)}
function Ma(a){function b(d){++Ga;La=a;Ka();a.ec(d);Ka();--Ga}if(a.dc)a.Bc=b,a.target.addEventListener(a.Zb,b,a.cc),J.push(a),Na||(ta.push(Ha),Na=!0);else for(var c=0;c<J.length;++c)J[c].target==a.target&&J[c].Zb==a.Zb&&Ia(c--)}var Oa={},Na,La,Pa,Qa,Ra,Sa,Ta=[0,document,window];function K(a){a=2<a?v(a):a;return Ta[a]||document.querySelector(a)}function Ua(a){return 0>Ta.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}var Va=[];
function Wa(a){var b=Va[a];b||(a>=Va.length&&(Va.length=a+1),Va[a]=b=pa.get(a));return b}
function Xa(a,b,c,d,e,g){Pa||(Pa=I(176));a={target:K(a),mc:!0,Zb:g,dc:d,ec:function(l){var n=Pa;E[n>>3]=l.timeStamp;var p=n>>2;B[p+2]=l.location;B[p+3]=l.ctrlKey;B[p+4]=l.shiftKey;B[p+5]=l.altKey;B[p+6]=l.metaKey;B[p+7]=l.repeat;B[p+8]=l.charCode;B[p+9]=l.keyCode;B[p+10]=l.which;y(l.key||"",x,n+44,32);y(l.code||"",x,n+76,32);y(l.char||"",x,n+108,32);y(l.locale||"",x,n+140,32);Wa(d)(e,n,b)&&l.preventDefault()},cc:c};Ma(a)}
function Ya(a,b,c){E[a>>3]=b.timeStamp;a>>=2;B[a+2]=b.screenX;B[a+3]=b.screenY;B[a+4]=b.clientX;B[a+5]=b.clientY;B[a+6]=b.ctrlKey;B[a+7]=b.shiftKey;B[a+8]=b.altKey;B[a+9]=b.metaKey;la[2*a+20]=b.button;la[2*a+21]=b.buttons;B[a+11]=b.movementX;B[a+12]=b.movementY;c=Ua(c);B[a+13]=b.clientX-c.left;B[a+14]=b.clientY-c.top}
function Za(a,b,c,d,e,g){Qa||(Qa=I(72));a=K(a);Ma({target:a,mc:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,Zb:g,dc:d,ec:function(l){l=l||event;Ya(Qa,l,a);Wa(d)(e,Qa,b)&&l.preventDefault()},cc:c})}
function $a(a,b,c,d){Ra||(Ra=I(36));a=K(a);Ma({target:a,Zb:"resize",dc:d,ec:function(e){e=e||event;if(e.target==a){var g=document.body;if(g){var l=Ra;B[l>>2]=e.detail;B[l+4>>2]=g.clientWidth;B[l+8>>2]=g.clientHeight;B[l+12>>2]=innerWidth;B[l+16>>2]=innerHeight;B[l+20>>2]=outerWidth;B[l+24>>2]=outerHeight;B[l+28>>2]=pageXOffset;B[l+32>>2]=pageYOffset;Wa(d)(10,l,b)&&e.preventDefault()}}},cc:c})}
function ab(a,b,c,d){Sa||(Sa=I(104));Ma({target:a,mc:!0,Zb:"wheel",dc:d,ec:function(e){e=e||event;var g=Sa;Ya(g,e,a);E[g+72>>3]=e.deltaX;E[g+80>>3]=e.deltaY;E[g+88>>3]=e.deltaZ;B[g+96>>2]=e.deltaMode;Wa(d)(9,g,b)&&e.preventDefault()},cc:c})}function bb(a){a.sc=a.getExtension("WEBGL_draw_instanced_base_vertex_base_instance")}function cb(a){a.wc=a.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance")}function db(a){a.jc=a.getExtension("WEBGL_multi_draw")}
var eb=1,L=[],M=[],fb=[],gb=[],N=[],O=[],hb=[],P=[],ib=[],jb=[],kb={},lb={};function Q(a){mb||(mb=a)}function nb(a){for(var b=eb++,c=a.length;c<b;c++)a[c]=null;return b}function ob(a,b){a.rc||(a.rc=a.getContext,a.getContext=function(d,e){e=a.rc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?pb(c,b):0}
function pb(a,b){var c=nb(P),d={Cc:c,attributes:b,version:b.Ec,Yb:a};a.canvas&&(a.canvas.zc=d);P[c]=d;("undefined"==typeof b.uc||b.uc)&&sb(d);return c}function sb(a){a||(a=S);if(!a.Dc){a.Dc=!0;var b=a.Yb;bb(b);cb(b);2<=a.version&&(b.tc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.tc)b.tc=b.getExtension("EXT_disjoint_timer_query");db(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var S,mb,tb=["default","low-power","high-performance"],ub={};function vb(){if(!wb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in ub)void 0===ub[b]?delete a[b]:a[b]=ub[b];var c=[];for(b in a)c.push(b+"="+a[b]);wb=c}return wb}var wb;function xb(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ia=!0}da(a,new Da(a))}
var yb=[null,[],[]],zb=[];function T(a,b,c,d){for(var e=0;e<a;e++){var g=U[c](),l=g&&nb(d);g?(g.name=l,d[l]=g):Q(1282);B[b+4*e>>2]=l}}
function Ab(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&Q(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=U.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>S.version){Q(1282);return}d=2*(U.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){Q(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=U.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:Q(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:B[b+4*a>>2]=e[a];break;case 2:D[b+4*a>>2]=e[a];break;case 4:A[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){Q(1280);
m("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:Q(1280);m("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;C[b>>2]=c;C[b+4>>2]=(c-C[b>>2])/4294967296;break;case 0:B[b>>2]=d;break;case 2:D[b>>2]=d;break;case 4:A[b>>0]=d?1:0}}else Q(1281)}function V(a){var b=z(a)+1,c=I(b);y(a,x,c,b);return c}
function Bb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function W(a){a-=5120;return 0==a?A:1==a?x:2==a?la:4==a?B:6==a?D:5==a||28922==a||28520==a||30779==a||30782==a?C:ma}function X(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Y(a){var b=U.Ac;if(b){var c=b.bc[a];"number"==typeof c&&(b.bc[a]=c=U.getUniformLocation(b,b.xc[a]+(0<c?"["+c+"]":"")));return c}Q(1282)}function Cb(a){return 0===a%4&&(0!==a%100||0===a%400)}
var Db=[31,29,31,30,31,30,31,31,30,31,30,31],Eb=[31,28,31,30,31,30,31,31,30,31,30,31];function Fb(a){var b=Array(z(a)+1);y(a,b,0,b.length);return b}
function Gb(a,b,c,d){function e(h,t,w){for(h="number"==typeof h?h.toString():h||"";h.length<t;)h=w[0]+h;return h}function g(h,t){return e(h,t,"0")}function l(h,t){function w(qb){return 0>qb?-1:0<qb?1:0}var R;0===(R=w(h.getFullYear()-t.getFullYear()))&&0===(R=w(h.getMonth()-t.getMonth()))&&(R=w(h.getDate()-t.getDate()));return R}function n(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function p(h){var t=h.$b;for(h=new Date((new Date(h.ac+1900,0,1)).getTime());0<t;){var w=h.getMonth(),R=(Cb(h.getFullYear())?Db:Eb)[w];if(t>R-h.getDate())t-=R-h.getDate()+1,h.setDate(1),11>w?h.setMonth(w+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+t);break}}w=new Date(h.getFullYear()+1,0,4);t=n(new Date(h.getFullYear(),
0,4));w=n(w);return 0>=l(t,h)?0>=l(w,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var q=B[d+40>>2];d={Hc:B[d>>2],Gc:B[d+4>>2],kc:B[d+8>>2],pc:B[d+12>>2],lc:B[d+16>>2],ac:B[d+20>>2],Wb:B[d+24>>2],$b:B[d+28>>2],Pc:B[d+32>>2],Fc:B[d+36>>2],Ic:q?v(q):""};c=v(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in q)c=c.replace(new RegExp(r,"g"),q[r]);var Z="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),rb="January February March April May June July August September October November December".split(" ");q={"%a":function(h){return Z[h.Wb].substring(0,3)},"%A":function(h){return Z[h.Wb]},"%b":function(h){return rb[h.lc].substring(0,3)},"%B":function(h){return rb[h.lc]},
"%C":function(h){return g((h.ac+1900)/100|0,2)},"%d":function(h){return g(h.pc,2)},"%e":function(h){return e(h.pc,2," ")},"%g":function(h){return p(h).toString().substring(2)},"%G":function(h){return p(h)},"%H":function(h){return g(h.kc,2)},"%I":function(h){h=h.kc;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){for(var t=0,w=0;w<=h.lc-1;t+=(Cb(h.ac+1900)?Db:Eb)[w++]);return g(h.pc+t,3)},"%m":function(h){return g(h.lc+1,2)},"%M":function(h){return g(h.Gc,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=
h.kc&&12>h.kc?"AM":"PM"},"%S":function(h){return g(h.Hc,2)},"%t":function(){return"\t"},"%u":function(h){return h.Wb||7},"%U":function(h){return g(Math.floor((h.$b+7-h.Wb)/7),2)},"%V":function(h){var t=Math.floor((h.$b+7-(h.Wb+6)%7)/7);2>=(h.Wb+371-h.$b-2)%7&&t++;if(t)53==t&&(w=(h.Wb+371-h.$b)%7,4==w||3==w&&Cb(h.ac)||(t=1));else{t=52;var w=(h.Wb+7-h.$b-1)%7;(4==w||5==w&&Cb(h.ac%400-1))&&t++}return g(t,2)},"%w":function(h){return h.Wb},"%W":function(h){return g(Math.floor((h.$b+7-(h.Wb+6)%7)/7),2)},
"%y":function(h){return(h.ac+1900).toString().substring(2)},"%Y":function(h){return h.ac+1900},"%z":function(h){h=h.Fc;var t=0<=h;h=Math.abs(h)/60;return(t?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Ic},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(r in q)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),q[r](d)));c=c.replace(/\0\0/g,"%");r=Fb(c);if(r.length>b)return 0;A.set(r,a);return r.length-1}
function Ba(a){for(var b="";;){var c=x[a++>>0];if(!c)return b;b+=String.fromCharCode(c)}}for(var U,Hb=0;32>Hb;++Hb)zb.push(Array(Hb));
var Ib={ib:function(){},F:function(){return 0},ab:function(){},cb:function(){return 0},_a:function(){},eb:function(){},$a:function(){},gb:function(){return!0},a:function(){fa("")},e:function(a,b,c){Fa.length=0;var d;for(c>>=2;d=x[b++];)c+=105!=d&c,Fa.push(105==d?B[c]:(106==d?na:E)[c++>>1]),++c;return Ca[a].apply(null,Fa)},D:function(a,b,c){a=K(a);if(!a)return-4;B[b>>2]=a.width;B[c>>2]=a.height},ta:function(){return devicePixelRatio},o:function(a,b,c){a=K(a);if(!a)return-4;a=Ua(a);E[b>>3]=a.width;
E[c>>3]=a.height;return 0},fb:()=>performance.now(),hb:function(a,b,c){x.copyWithin(a,b,b+c)},Ya:function(a){var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-d%65536)%65536);a:{try{ha.grow(e-ka.byteLength+65535>>>16);oa();var g=1;break a}catch(l){}g=void 0}if(g)return!0}return!1},C:function(a,b,c){a=K(a);if(!a)return-4;a.width=b;a.height=c;return 0},lb:function(a,b,c,d){Xa(a,
b,c,d,2,"keydown");return 0},db:function(a,b,c,d){Xa(a,b,c,d,3,"keyup");return 0},N:function(a,b,c,d){Za(a,b,c,d,5,"mousedown");return 0},Fb:function(a,b,c,d){Za(a,b,c,d,8,"mousemove");return 0},Ob:function(a,b,c,d){Za(a,b,c,d,6,"mouseup");return 0},T:function(a,b,c,d){$a(a,b,c,d);return 0},vb:function(a,b,c,d){a=K(a);return"undefined"!=typeof a.onwheel?(ab(a,b,c,d),0):-1},Wa:function(){return S&&S.Yb&&S.attributes.vc?0:-3},ka:function(a,b){b>>=2;b={alpha:!!B[b],depth:!!B[b+1],stencil:!!B[b+2],antialias:!!B[b+
3],premultipliedAlpha:!!B[b+4],preserveDrawingBuffer:!!B[b+5],powerPreference:tb[B[b+6]],failIfMajorPerformanceCaveat:!!B[b+7],Ec:B[b+8],Lc:B[b+9],uc:B[b+10],vc:B[b+11],Mc:B[b+12],Nc:B[b+13]};a=K(a);return!a||b.vc?0:ob(a,b)},Pb:function(a){S==a&&(S=0);S===P[a]&&(S=null);if("object"==typeof Oa)for(var b=P[a].Yb.canvas,c=0;c<J.length;++c)J[c].target!=b||Ia(c--);P[a]&&P[a].Yb.canvas&&(P[a].Yb.canvas.zc=void 0);P[a]=null},nb:function(a,b){a=P[a];b=v(b);b.startsWith("GL_")&&(b=b.substr(3));"WEBGL_draw_instanced_base_vertex_base_instance"==
b&&bb(U);"WEBGL_multi_draw_instanced_base_vertex_base_instance"==b&&cb(U);"WEBGL_multi_draw"==b&&db(U);return!!a.Yb.getExtension(b)},ob:function(){return S?S.Cc:0},Da:function(a){a>>=2;for(var b=0;14>b;++b)B[a+b]=0;B[a]=B[a+1]=B[a+3]=B[a+4]=B[a+8]=B[a+10]=1},ba:function(a){S=P[a];f.Kc=U=S&&S.Yb;return!a||U?0:-5},jb:function(a,b){var c=0;vb().forEach(function(d,e){var g=b+c;e=C[a+4*e>>2]=g;for(g=0;g<d.length;++g)A[e++>>0]=d.charCodeAt(g);A[e>>0]=0;c+=d.length+1});return 0},kb:function(a,b){var c=vb();
C[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});C[b>>2]=d;return 0},v:xb,G:function(){return 52},bb:function(){return 52},Za:function(){return 70},E:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var l=C[b>>2],n=C[b+4>>2];b+=8;for(var p=0;p<n;p++){var q=x[l+p],r=yb[a];if(0===q||10===q){for(q=0;r[q]&&!(NaN<=q);)++q;q=ja.decode(r.buffer?r.subarray(0,q):new Uint8Array(r.slice(0,q)));(1===a?ea:m)(q);r.length=0}else r.push(q)}e+=n}C[d>>2]=e;return 0},b:function(a){U.activeTexture(a)},Ca:function(a,
b){U.attachShader(M[a],O[b])},x:function(a,b){35051==a?U.nc=b:35052==a&&(U.Xb=b);U.bindBuffer(a,L[b])},k:function(a,b,c){U.bindBufferBase(a,b,L[c])},w:function(a,b,c,d,e){U.bindBufferRange(a,b,L[c],d,e)},c:function(a,b){U.bindFramebuffer(a,fb[b])},H:function(a,b){U.bindRenderbuffer(a,gb[b])},A:function(a,b){U.bindTexture(a,N[b])},p:function(a,b){U.bindTransformFeedback(a,jb[b])},m:function(a){U.bindVertexArray(hb[a])},Lb:function(a,b){U.blendFunc(a,b)},Ua:function(a,b,c,d,e,g,l,n,p,q){U.blitFramebuffer(a,
b,c,d,e,g,l,n,p,q)},K:function(a,b,c,d){c&&b?U.bufferData(a,x,d,c,b):U.bufferData(a,b,d)},J:function(a,b,c,d){c&&U.bufferSubData(a,b,x,d,c)},Qa:function(a){return U.checkFramebufferStatus(a)},Ta:function(a){U.clear(a)},Ma:function(a,b,c,d){U.clearBufferfi(a,b,c,d)},Na:function(a,b,c){U.clearBufferfv(a,b,D,c>>2)},Pa:function(a,b,c){U.clearBufferiv(a,b,B,c>>2)},Oa:function(a,b,c){U.clearBufferuiv(a,b,C,c>>2)},t:function(a,b,c,d){U.clearColor(a,b,c,d)},Kb:function(a){U.clearDepth(a)},Gb:function(a){U.compileShader(O[a])},
z:function(a,b,c,d,e,g,l,n,p){U.Xb||!n?U.compressedTexSubImage2D(a,b,c,d,e,g,l,n,p):U.compressedTexSubImage2D(a,b,c,d,e,g,l,x,p,n)},aa:function(a,b,c,d,e,g,l,n,p,q,r){U.Xb?U.compressedTexSubImage3D(a,b,c,d,e,g,l,n,p,q,r):U.compressedTexSubImage3D(a,b,c,d,e,g,l,n,p,x,r,q)},O:function(a,b,c,d,e){U.copyBufferSubData(a,b,c,d,e)},Ia:function(a,b,c,d,e,g,l,n){U.copyTexSubImage2D(a,b,c,d,e,g,l,n)},Ha:function(a,b,c,d,e,g,l,n,p){U.copyTexSubImage3D(a,b,c,d,e,g,l,n,p)},Ga:function(){var a=nb(M),b=U.createProgram();
b.name=a;b.ic=b.fc=b.hc=0;b.qc=1;M[a]=b;return a},Jb:function(a){var b=nb(O);O[b]=U.createShader(a);return b},P:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=L[d];e&&(U.deleteBuffer(e),e.name=0,L[d]=null,d==U.nc&&(U.nc=0),d==U.Xb&&(U.Xb=0))}},Fa:function(a){if(a){var b=M[a];b?(U.deleteProgram(b),b.name=0,M[a]=null):Q(1281)}},Ib:function(a){if(a){var b=O[a];b?(U.deleteShader(b),O[a]=null):Q(1281)}},na:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2],e=N[d];e&&(U.deleteTexture(e),e.name=
0,N[d]=null)}},W:function(a,b){for(var c=0;c<a;c++){var d=B[b+4*c>>2];U.deleteVertexArray(hb[d]);hb[d]=null}},I:function(a){U.depthFunc(a)},n:function(a){U.disable(a)},$:function(a,b,c){U.drawArrays(a,b,c)},Z:function(a,b,c,d){U.drawArraysInstanced(a,b,c,d)},wb:function(a,b,c,d,e){U.sc.drawArraysInstancedBaseInstanceWEBGL(a,b,c,d,e)},La:function(a,b){for(var c=zb[a],d=0;d<a;d++)c[d]=B[b+4*d>>2];U.drawBuffers(c)},_:function(a,b,c,d){U.drawElements(a,b,c,d)},Y:function(a,b,c,d,e){U.drawElementsInstanced(a,
b,c,d,e)},l:function(a,b,c,d,e,g,l){U.sc.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,d,e,g,l)},h:function(a){U.enable(a)},V:function(a){U.enableVertexAttribArray(a)},zb:function(a,b,c,d){U.framebufferRenderbuffer(a,b,c,gb[d])},yb:function(a,b,c,d,e){U.framebufferTexture2D(a,b,c,N[d],e)},xb:function(a,b,c,d,e){U.framebufferTextureLayer(a,b,N[c],d,e)},Q:function(a,b){T(a,b,"createBuffer",L)},Ab:function(a,b){T(a,b,"createFramebuffer",fb)},pb:function(a,b){T(a,b,"createQuery",ib)},Db:function(a,
b){T(a,b,"createRenderbuffer",gb)},oa:function(a,b){T(a,b,"createTexture",N)},mb:function(a,b){T(a,b,"createTransformFeedback",jb)},X:function(a,b){T(a,b,"createVertexArray",hb)},ma:function(a){U.generateMipmap(a)},M:function(a,b,c){c?B[c>>2]=U.getBufferParameter(a,b):Q(1281)},L:function(a,b,c,d){d?c&&U.getBufferSubData(a,b,x,d,c):Q(1281)},pa:function(a,b){Ab(a,b,2)},i:function(a,b){Ab(a,b,0)},Ea:function(a,b,c,d){a=U.getProgramInfoLog(M[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,x,d,b):0;c&&
(B[c>>2]=b)},r:function(a,b,c){if(c)if(a>=eb)Q(1281);else if(a=M[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),B[c>>2]=a.length+1;else if(35719==b){if(!a.ic)for(b=0;b<U.getProgramParameter(a,35718);++b)a.ic=Math.max(a.ic,U.getActiveUniform(a,b).name.length+1);B[c>>2]=a.ic}else if(35722==b){if(!a.fc)for(b=0;b<U.getProgramParameter(a,35721);++b)a.fc=Math.max(a.fc,U.getActiveAttrib(a,b).name.length+1);B[c>>2]=a.fc}else if(35381==b){if(!a.hc)for(b=0;b<U.getProgramParameter(a,35382);++b)a.hc=
Math.max(a.hc,U.getActiveUniformBlockName(a,b).length+1);B[c>>2]=a.hc}else B[c>>2]=U.getProgramParameter(a,b);else Q(1281)},Eb:function(a,b,c,d){a=U.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?y(a,x,d,b):0;c&&(B[c>>2]=b)},s:function(a,b,c){c?35716==b?(a=U.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),B[c>>2]=a?a.length+1:0):35720==b?(a=U.getShaderSource(O[a]),B[c>>2]=a?a.length+1:0):B[c>>2]=U.getShaderParameter(O[a],b):Q(1281)},f:function(a){var b=kb[a];if(!b){switch(a){case 7939:b=
U.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=V(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||Q(1280);b=b&&V(b);break;case 7938:b=V("OpenGL ES 3.0 ("+U.getParameter(7938)+")");break;case 35724:b=U.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=V(b);break;default:Q(1280)}kb[a]=b}return b},u:function(a,b){if(2>S.version)return Q(1282),
0;var c=lb[a];if(c)return 0>b||b>=c.length?(Q(1281),0):c[b];switch(a){case 7939:return c=U.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return V(d)}),c=lb[a]=c,0>b||b>=c.length?(Q(1281),0):c[b];default:return Q(1280),0}},za:function(a,b){return U.getUniformBlockIndex(M[a],v(b))},Aa:function(a,b){b=v(b);if(a=M[a]){var c=a,d=c.bc,e=c.yc,g;if(!d)for(c.bc=d={},c.xc={},g=0;g<U.getProgramParameter(c,35718);++g){var l=U.getActiveUniform(c,g);var n=l.name;
l=l.size;var p=Bb(n);p=0<p?n.slice(0,p):n;var q=c.qc;c.qc+=l;e[p]=[l,q];for(n=0;n<l;++n)d[q]=n,c.xc[q++]=p}c=a.bc;d=0;e=b;g=Bb(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.yc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else Q(1281);return-1},Sa:function(a,b,c){for(var d=zb[b],e=0;e<b;e++)d[e]=B[c+4*e>>2];U.invalidateFramebuffer(a,d)},Ra:function(a,b,c,d,e,g,l){for(var n=zb[b],p=0;p<b;p++)n[p]=B[c+4*p>>2];U.invalidateSubFramebuffer(a,n,d,e,g,l)},Ba:function(a){a=
M[a];U.linkProgram(a);a.bc=0;a.yc={}},tb:function(a,b,c,d){U.jc.multiDrawArraysWEBGL(a,B,b>>2,B,c>>2,d)},rb:function(a,b,c,d,e){U.jc.multiDrawArraysInstancedWEBGL(a,B,b>>2,B,c>>2,B,d>>2,e)},qb:function(a,b,c,d,e,g){U.wc.multiDrawArraysInstancedBaseInstanceWEBGL(a,B,b>>2,B,c>>2,B,d>>2,C,e>>2,g)},ub:function(a,b,c,d,e){U.jc.multiDrawElementsWEBGL(a,B,b>>2,c,B,d>>2,e)},sb:function(a,b,c,d,e,g){U.jc.multiDrawElementsInstancedWEBGL(a,B,b>>2,c,B,d>>2,B,e>>2,g)},y:function(a,b,c,d,e,g,l,n){U.wc.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,
B,b>>2,c,B,d>>2,B,e>>2,B,g>>2,C,l>>2,n)},j:function(a,b){U.pixelStorei(a,b)},Nb:function(a,b){U.polygonOffset(a,b)},Ka:function(a){U.readBuffer(a)},Ja:function(a,b,c,d,e,g,l){if(U.nc)U.readPixels(a,b,c,d,e,g,l);else{var n=W(g);U.readPixels(a,b,c,d,e,g,n,l>>X(n))}},Cb:function(a,b,c,d){U.renderbufferStorage(a,b,c,d)},Bb:function(a,b,c,d,e){U.renderbufferStorageMultisample(a,b,c,d,e)},Mb:function(a,b,c,d){U.scissor(a,b,c,d)},Hb:function(a,b,c,d){for(var e="",g=0;g<b;++g){var l=d?B[d+4*g>>2]:-1;e+=v(B[c+
4*g>>2],0>l?void 0:l)}U.shaderSource(O[a],e)},ea:function(a,b,c,d,e,g,l,n,p){if(U.Xb)U.texImage2D(a,b,c,d,e,g,l,n,p);else if(p){var q=W(n);U.texImage2D(a,b,c,d,e,g,l,n,q,p>>X(q))}else U.texImage2D(a,b,c,d,e,g,l,n,null)},da:function(a,b,c,d,e,g,l,n,p,q){if(U.Xb)U.texImage3D(a,b,c,d,e,g,l,n,p,q);else if(q){var r=W(p);U.texImage3D(a,b,c,d,e,g,l,n,p,r,q>>X(r))}else U.texImage3D(a,b,c,d,e,g,l,n,p,null)},ja:function(a,b,c){U.texParameterf(a,b,c)},ha:function(a,b,c){U.texParameterf(a,b,D[c>>2])},la:function(a,
b,c){U.texParameteri(a,b,c)},ia:function(a,b,c){U.texParameteri(a,b,B[c>>2])},ga:function(a,b,c,d,e){U.texStorage2D(a,b,c,d,e)},fa:function(a,b,c,d,e,g){U.texStorage3D(a,b,c,d,e,g)},q:function(a,b,c,d,e,g,l,n,p){if(U.Xb)U.texSubImage2D(a,b,c,d,e,g,l,n,p);else if(p){var q=W(n);U.texSubImage2D(a,b,c,d,e,g,l,n,q,p>>X(q))}else U.texSubImage2D(a,b,c,d,e,g,l,n,null)},ca:function(a,b,c,d,e,g,l,n,p,q,r){if(U.Xb)U.texSubImage3D(a,b,c,d,e,g,l,n,p,q,r);else if(r){var Z=W(q);U.texSubImage3D(a,b,c,d,e,g,l,n,p,
q,Z,r>>X(Z))}else U.texSubImage3D(a,b,c,d,e,g,l,n,p,q,null)},B:function(a,b,c,d){a=M[a];for(var e=[],g=0;g<b;g++)e.push(v(B[c+4*g>>2]));U.transformFeedbackVaryings(a,e,d)},ya:function(a,b){U.uniform1f(Y(a),b)},va:function(a,b,c){b&&U.uniform1fv(Y(a),D,c>>2,b)},wa:function(a,b){U.uniform1i(Y(a),b)},ua:function(a,b,c){b&&U.uniform3fv(Y(a),D,c>>2,3*b)},xa:function(a,b,c,d,e){U.uniform4f(Y(a),b,c,d,e)},sa:function(a,b,c){b&&U.uniform4fv(Y(a),D,c>>2,4*b)},d:function(a,b,c){a=M[a];U.uniformBlockBinding(a,
b,c)},ra:function(a,b,c,d){b&&U.uniformMatrix3fv(Y(a),!!c,D,d>>2,9*b)},qa:function(a,b,c,d){b&&U.uniformMatrix4fv(Y(a),!!c,D,d>>2,16*b)},g:function(a){a=M[a];U.useProgram(a);U.Ac=a},R:function(a,b){U.vertexAttribDivisor(a,b)},U:function(a,b,c,d,e){U.vertexAttribIPointer(a,b,c,d,e)},S:function(a,b,c,d,e,g){U.vertexAttribPointer(a,b,c,!!d,e,g)},Va:function(a,b,c,d){U.viewport(a,b,c,d)},Xa:function(a,b,c,d){return Gb(a,b,c,d)}};
(function(){function a(e){f.asm=e.exports;ha=f.asm.Qb;oa();pa=f.asm.Ub;ra.unshift(f.asm.Rb);F--;f.monitorRunDependencies&&f.monitorRunDependencies(F);0==F&&(null!==wa&&(clearInterval(wa),wa=null),G&&(e=G,G=null,e()))}function b(e){a(e.instance)}function c(e){return Aa().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){m("failed to asynchronously prepare wasm: "+g);fa(g)})}var d={a:Ib};F++;f.monitorRunDependencies&&f.monitorRunDependencies(F);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return m("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return u||"function"!=typeof WebAssembly.instantiateStreaming||xa()||"function"!=typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){m("wasm streaming compile failed: "+g);m("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.Rb).apply(null,arguments)};var I=f._malloc=function(){return(I=f._malloc=f.asm.Sb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.Tb).apply(null,arguments)};var Jb=f.stackAlloc=function(){return(Jb=f.stackAlloc=f.asm.Vb).apply(null,arguments)};f.AsciiToString=Ba;var Kb;G=function Lb(){Kb||Mb();Kb||(G=Lb)};
function Nb(a){var b=f._main;a=a||[];a.unshift(ca);var c=a.length,d=Jb(4*(c+1)),e=d>>2;a.forEach(l=>{var n=B,p=e++,q=z(l)+1,r=Jb(q);y(l,A,r,q);n[p]=r});B[e]=0;try{var g=b(c,d);xb(g,!0)}catch(l){l instanceof Da||"unwind"==l||da(1,l)}}
function Mb(){function a(){if(!Kb&&(Kb=!0,f.calledRun=!0,!ia)){Ea(ra);Ea(sa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Ob&&Nb(b);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();ua.unshift(c)}Ea(ua)}}var b=b||ba;if(!(0<F)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)va();Ea(qa);0<F||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);
a()},1)):a())}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Ob=!0;f.noInitialRun&&(Ob=!1);Mb();
